"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";
import { LayoutProvider, useLayout } from "./_context/layout";
import { NavigationBar } from "./_components/NavigationBar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <LayoutProvider>
        <body
          className={`${inter.className}flex min-h-screen flex-col items-center  p-24`}
        >
          <NavigationBar />
          <main className="flex flex-col items-center justify-between p-24">
            {children}
          </main>
        </body>
      </LayoutProvider>
    </html>
  );
}
